elementweb:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.127-0-0-1.nip.io"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &frontend_host chat.127-0-0-1.nip.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  config:
    default:
      base_url: https://matrix.127-0-0-1.nip.io
      server_name: 127-0-0-1.nip.io

dendrite:
  dendrite_config:
    global:
      server_name: matrix.ramirodelcorro.com
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hostName: matrix.ramirodelcorro.com
    tls:
      - hosts:
          - matrix.ramirodelcorro.com
        secretName: matrix-tls-certificate
  postgresql:
    enabled: true
